### ISSUE TITLE
Output AWS Shapes

### ISSUE THREAD

**Issue by ofosos** [benbc/cloud-formation-viz#8]
Hi Ben,
do you mind, if I extend the cfviz to support AWS shapes? I'd like to send a pull request this weekend.

Cheers, Mark

**Comment by benbc** [comment]
Hello @ofosos. That sounds really cool. Maybe make it optional so it's still possible to get an uncluttered version?

**Comment by benbc** [comment]
@ofosos I'm going to close this, assuming that it's no longer important to you. Please reopen if you're still interested in it.
